language:
  - python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_script:
  - pip3 install aiohttp>=3.6.0
  - pip3 install requests>=2.22.0
  - cd danbotstatus
script:
  - python3 errors.py
  - python3 asynchronous.py
  - python3 synchronous.py
